/** NCERT chapter titles per class and subject, for the chapter picker. Chapters whose full text
 * is in the database are grounded with page refs; the rest are generated from the chapter title. */
export interface CatalogBook {
  grade: number;
  subject: string;
  book: string;
  chapters: string[];
}

export const NCERT_CATALOG: CatalogBook[] = [
  {
    grade: 6,
    subject: "Science",
    book: "Curiosity",
    chapters: [
      "The Wonderful World of Science",
      "Diversity in the Living World",
      "Mindful Eating: A Path to a Healthy Body",
      "Exploring Magnets",
      "Measurement of Length and Motion",
      "Materials Around Us",
      "Temperature and its Measurement",
      "A Journey through States of Water",
      "Methods of Separation in Everyday Life",
      "Living Creatures: Exploring their Characteristics",
      "Nature's Treasures",
      "Beyond Earth",
    ],
  },
  {
    grade: 6,
    subject: "Maths",
    book: "Ganita Prakash",
    chapters: [
      "Patterns in Mathematics",
      "Lines and Angles",
      "Number Play",
      "Data Handling and Presentation",
      "Prime Time",
      "Perimeter and Area",
      "Fractions",
      "Playing with Constructions",
      "Symmetry",
      "The Other Side of Zero",
    ],
  },
  {
    grade: 7,
    subject: "Science",
    book: "Curiosity",
    chapters: [
      "The Ever-Evolving World of Science",
      "Exploring Substances: Acidic, Basic, and Neutral",
      "Electricity: Circuits and their Components",
      "The World of Metals and Non-metals",
      "Changes Around Us: Physical and Chemical",
      "Adolescence: A Stage of Growth and Change",
      "Heat Transfer in Nature",
      "Measurement of Time and Motion",
      "Life Processes in Animals",
      "Life Processes in Plants",
      "Light: Shadows and Reflections",
      "Earth, Moon, and the Sun",
    ],
  },
  {
    grade: 7,
    subject: "Maths",
    book: "Ganita Prakash",
    chapters: [
      "Large Numbers Around Us",
      "Arithmetic Expressions",
      "A Peek Beyond the Point",
      "Expressions using Letter-Numbers",
      "Parallel and Intersecting Lines",
      "Number Play",
      "A Tale of Three Intersecting Lines",
      "Working with Fractions",
    ],
  },
  {
    grade: 8,
    subject: "Science",
    book: "Science",
    chapters: [
      "Crop Production and Management",
      "Microorganisms: Friend and Foe",
      "Coal and Petroleum",
      "Combustion and Flame",
      "Conservation of Plants and Animals",
      "Reproduction in Animals",
      "Reaching the Age of Adolescence",
      "Force and Pressure",
      "Friction",
      "Sound",
      "Chemical Effects of Electric Current",
      "Some Natural Phenomena",
      "Light",
    ],
  },
  {
    grade: 8,
    subject: "Maths",
    book: "Mathematics",
    chapters: [
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Understanding Quadrilaterals",
      "Data Handling",
      "Squares and Square Roots",
      "Cubes and Cube Roots",
      "Comparing Quantities",
      "Algebraic Expressions and Identities",
      "Mensuration",
      "Exponents and Powers",
      "Direct and Inverse Proportions",
      "Factorisation",
      "Introduction to Graphs",
    ],
  },
  {
    grade: 9,
    subject: "Science",
    book: "Science",
    chapters: [
      "Matter in Our Surroundings",
      "Is Matter Around Us Pure?",
      "Atoms and Molecules",
      "Structure of the Atom",
      "The Fundamental Unit of Life",
      "Tissues",
      "Motion",
      "Force and Laws of Motion",
      "Gravitation",
      "Work and Energy",
      "Sound",
      "Improvement in Food Resources",
    ],
  },
  {
    grade: 9,
    subject: "Maths",
    book: "Mathematics",
    chapters: [
      "Number Systems",
      "Polynomials",
      "Coordinate Geometry",
      "Linear Equations in Two Variables",
      "Introduction to Euclid's Geometry",
      "Lines and Angles",
      "Triangles",
      "Quadrilaterals",
      "Circles",
      "Heron's Formula",
      "Surface Areas and Volumes",
      "Statistics",
    ],
  },
  {
    grade: 10,
    subject: "Science",
    book: "Science",
    chapters: [
      "Chemical Reactions and Equations",
      "Acids, Bases and Salts",
      "Metals and Non-metals",
      "Carbon and its Compounds",
      "Life Processes",
      "Control and Coordination",
      "How do Organisms Reproduce?",
      "Heredity",
      "Light – Reflection and Refraction",
      "The Human Eye and the Colourful World",
      "Electricity",
      "Magnetic Effects of Electric Current",
      "Our Environment",
    ],
  },
  {
    grade: 10,
    subject: "Maths",
    book: "Mathematics",
    chapters: [
      "Real Numbers",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Arithmetic Progressions",
      "Triangles",
      "Coordinate Geometry",
      "Introduction to Trigonometry",
      "Some Applications of Trigonometry",
      "Circles",
      "Areas Related to Circles",
      "Surface Areas and Volumes",
      "Statistics",
      "Probability",
    ],
  },
];
